### PR TITLE
Fix multi tools

### PR DESCRIPTION
**Pull request by tectiv3**
Without this fix arguments from multiple tools were gathered into one property and caused json parse error

### CODE REVIEW

**Comment by tectiv3** [comment]
Do not merge just yet please. It needs some more testing.

**Comment by tectiv3** [comment]
ready. works without a hitch now

**Comment by tectiv3** [comment]
Just found a different approach in langchain repo
https://github.com/tmc/langchaingo/blob/141844a55455cd79251ab9a9f1f4932016b4593b/llms/openai/internal/openaiclient/chat.go#L422

**Comment by meinside** [comment]
👍 great!

**Comment by meinside** [comment]
Is it okay to release a new version with it?
I have no billing-enabled account for now, so I couldn't run the tests.

**Comment by tectiv3** [comment]
I can run the tests and let you know in a couple of hours

**Comment by tectiv3** [comment]
Though I've been using it in my own fork for days now - no problems.

**Comment by tectiv3** [comment]
yeah, tests need fixing

**Pull request merged**
